### ISSUE TITLE
CE Table

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#10]
1. get from the user number of significant digits to round the Cost, Health and ICER to. 
2. print table to the console 
3. print table to a csv file

**Comment by rezayas** [comment]
Looks great. Just one comment: we might need to round each (cost, health, and ICER) to a different number. so instead of `digits=5`, could you get `cost_digits=0, effect_digits=2, icer_digits=0`?

**Comment by yanqi8** [comment]
Done. By the way, the two Incremental columns show 2 digits in the output.

**Comment by rezayas** [comment]
Looks very good... One more thing: The column `'E[dCost]'] `should have the same digits as `'E[Cost]'` and the column `'E[dEffect]'` should have the same digits as `'E[Effect]'`. Thanks!

**Comment by yanqi8** [comment]
OK, done!
