### ISSUE TITLE
ICER

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#11]
functions `get_CI` and `get_PI` in `ICER_indp`

**Comment by yanqi8** [comment]
Updated. You can try the functions in **TestEconEvalClasses.py** under "scr".
I also did a minor change in ICER_paired, since cost and health are paired as one observation, so I think we only need to sample once.

**Comment by rezayas** [comment]
Thank you. I agree. 
I added one more test to `TestEconEval.py` and the calculated confidence interval and prediction interval for ICER_indp do not seem correct. Would you mind checking?

**Comment by yanqi8** [comment]
I believe I made a typo in the file. Sorry for that!
now I get test results like:
Paired:
(966.66666666666652, array([  783.33333333,  1166.66666667]), [777.49999999999977, 1141.6666666666665])
Independent:
(966.66666666666652, array([  578.88888889,  2573.33333333]), [598.75, 1524.9999999999995])

**Comment by rezayas** [comment]
perfect thank you.
