### ISSUE TITLE
CEPlot.py

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#12]
1. To initialize `CEA` class, strategies are provided in `list` format. Could we modify the code so that `self._strategiesOnFrontier` is also the `list` of strategies that are on the frontier? 
2. And could we also assign `self._strategiesNotOnFrontier` to the list of strategies that are not on the frontier?

**Comment by yanqi8** [comment]
Updated. self._strategiesOnFrontier now is a list of Strategy objects.

**Comment by rezayas** [comment]
Could you also include the individual cost and effect observations for each strategy (i.e. `self.costObs` and `self.effectObs`) for the list of returned strategies. This is for people who want to do some additional analysis on these strategies.

**Comment by yanqi8** [comment]
Updated. The new version finds the dominated / not dominated ones' index, and put corresponding strategy object (origin object from input) in list.

**Comment by rezayas** [comment]
**[Make sure to pull first.]**

Excellent. A couple of cosmetic comments:
1. Could we make the figure (the main frame) square?
2. Could we move the labels a little closer to their arrows? 

And note that the test code is now located under the \tests folder.

**Comment by yanqi8** [comment]
Sure, updated.
1. The figure size is controlled by **plt.figure(figsize=(a,b))**, and I add an argument called figure_size to enable users to customize it.
2. The distance is controlled by the pad argument in **bbox=dict(pad=-4, facecolor="none", edgecolor="none")**
3. The legends are set by **plt.legend(loc='upper left', numpoints=1, ncol=3, fontsize=8)**, and you can change the location of it using the loc argument.

**Comment by rezayas** [comment]
**[Pull First]**

Thank you Yan. Looks great. One more cosmetic comment: When `show_clouds=False` can we remove the arrows and make the labels just a little closer to the dots?

**Comment by yanqi8** [comment]
Okay I removed the arrows

**Comment by rezayas** [comment]
great thank you.
