### ISSUE TITLE
CEA

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#13]
First, notice that I changed the set up in `TestCEPlot.py` so that the strategy `s0` is not on the origin any more. This is more realistic. So now, let's assume that the first strategy in the list `strategies` always represents the "base" strategy, and so we need to move the origin to this strategy:  

The the `__init__` function of class `CEA` should be modified such that it takes a new argument `if_paired`. 

`if_paired = False` then subtract E[cost] and E[effect] of the first strategy from the E[cost] and E[effect] of all strategies so that the first strategy is now on the origin. 
And 
`if_paired = False` the subtract cost_i and effect_i of the first strategy from cost_i and effect_i of all strategies so that the first strategy is now on the origin.

**Comment by yanqi8** [comment]
Done. But for **self._strategiesOnFrontier** and **self._strategiesNotOnFrontier**
I still output the original data. Do you want to return data points after shifting too?

**Comment by rezayas** [comment]
looks great! 

When observations across strategies are **paired,** we calculate the element-wise differences between cost and effect (with respect to the first strategy) otherwise, we subtract the mean of first observations from the cost and effect elements of all strategies.

I think your code was doing the opposite. I corrected it (i think) but I wanted to check with you that the new code looks correct to you too. 

```
        if if_paired:
            for i in range(self._n):
                shifted_strategy = Strategy(strategies[i].name,
                                            strategies[i].costObs-strategies[0].costObs,
                                            strategies[i].effectObs-strategies[0].effectObs)
                shifted_strategies.append(shifted_strategy)

        else:  # if not paired
            e_cost = strategies[0].aveCost
            e_effect = strategies[0].aveEffect
            for i in range(self._n):
                shifted_strategy = Strategy(strategies[i].name,
                                            strategies[i].costObs - e_cost,
                                            strategies[i].effectObs - e_effect)
                shifted_strategies.append(shifted_strategy)
```

**Comment by yanqi8** [comment]
Yes that looks right. Sorry for the confusion ; P
