### ISSUE TITLE
Fitting probability distributions 

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#15]
Would you include some sample code to fit probability distributions to some randomly generated data?  I have added `ProbDistFitting.py` for this purpose. The sample code should show the histogram of the data on which the fitted probability distribution is overlaid.

 Let's start with **Poisson,** and **Gamma** for now.

**Comment by yanqi8** [comment]
Done!

**Comment by rezayas** [comment]
Thank you. Had two comments:
1. The gamma looks good. Is it possible to also return some **measure of fit** (such as Akaike information criterion (AIC)) or something similar so that we can quantitatively compare the fit of difference distributions to the data?
2. For the Poisson distribution, I don't think `curve_fit` find the **maximum likelihood estimators**. Can we find an alternative approach to get the ML estimators?

**Comment by yanqi8** [comment]
Updated, I returned AIC in each function.

**Comment by rezayas** [comment]
This is great. I made some changes to make sure the code is reusable and the histograms still stay nice when we change the input data.

One questions: for the Poisson histogram, can we use step functions to display the fitted Poisson distribution? 

https://matplotlib.org/gallery/lines_bars_and_markers/step_demo.html#sphx-glr-gallery-lines-bars-and-markers-step-demo-py

**Comment by yanqi8** [comment]
Sure, changed it!

**Comment by rezayas** [comment]
Looks super nice. Thank you!
