### ISSUE TITLE
y-axis of cost-effective figure

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#16]
Would it be possible to format the numbers on the y-axis of the cost-effectiveness figure (in [EconEvalClasses.py](https://github.com/HPM573/HPM573_SupportLib/blob/master/scr/EconEvalClasses.py)) such that they are rounded to an integer and have 1000 separator (,) if needed?

**Comment by yanqi8** [comment]
I set the format of y-axis to int and thousands. While our CE plane is based on shifted data, the plot in the original test file probably won't change.

**Comment by rezayas** [comment]
This looks nice. But now when I run [CompareTherapies.py](https://github.com/HPM573/Labs_MarkovModel/blob/master/CompareTherapies.py), the label of the y-axis is vanished. Do you get the same thing? 

![image](https://user-images.githubusercontent.com/25065190/37414132-d0f3bc12-277e-11e8-9f4a-41357aba833a.png)

**Comment by yanqi8** [comment]
I think that's due to the larger area of yticks needed now. Put in a larger **figure_size** in the argument should fixed it.
