### ISSUE TITLE
get shifted strategies

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#17]
I know you asked me before and I answered no but now I think it's often needed to get the **shifted** strategies that are on the frontier and not on the frontier. So would you please implement the following two methods in the `CEA` class?

```
def get_shifted_strategies_on_frontier(self):
def get_shifted_strategies_not_on_frontier(self):
```

And remember both need to return a `list` (not data frame).

**Comment by yanqi8** [comment]
No problem, updated.
