### ISSUE TITLE
Relative difference

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#18]
I have added three new classes at the end of [StatisticalClasses.py](https://github.com/HPM573/HPM573_SupportLib/blob/master/scr/StatisticalClasses.py) to make inference about the random variable (X-Y)/X. 

Whenever you have a chance, would you please implement these classes (they will look similar to `_RatioStat` , `RatioStatPaired`, and `RatioStatIndp` classes). 

And note that since (X-Y)/X = 1-Y/X, you can tie these new classes to the corresponding ratio classes.

**Comment by yanqi8** [comment]
No problem. By the way, as our other ratio classes are defined as X/Y, can I change the definition of this new class to (Y - X)/Y = 1 - X/Y ?

**Comment by rezayas** [comment]
Great point. I updated the `__init__ `function of `RelativeDifference `class to make it explicit. So we are interested in making inference about: (X-Y_reference)/Y_reference.

**Comment by rezayas** [comment]
Sorry I guess we were working on the same thing at the same time. but there was not conflict in the code. Just make sure that you are using `x `and `y_reference `in your implementation so that there is not confusion about the denominator.

**Comment by yanqi8** [comment]
No worries, now it returns results for (X/Y - 1).
