### ISSUE TITLE
Additional distributions to fit

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#19]
Whenever you get a chance, would you please write the code (and the test code) to fit these distributions to some synthesized data?

1. **Exponential**
2. **Beta** (note that the data may not necessarily fall within 0 and 1, so we should take `min` and `max` as optional arguments for `fit_beta()`. If they are not provided, they the code needs to find the min and max from the data. 
3. **BetaBinomial**
4. **Binomial**
5. **Empirical** (I guess for this, we just need to return the frequency of each observation)
6. **Gamma**
7. **GammaPoisson**
8. **Geometric**
9. **JohnsonSb**
10. **JohnsonSu**
11. **LogNormal**
12.  **NegativeBinomial**
13. **Normal**
14. **Triangular** 
15. **Uniform**
16. **UniformDiscrete**
17. **Weibull**

Some must be easy some more challenging. So let me know if you have any questions!

**Comment by yanqi8** [comment]
I'm not sure I understand the question for beta distribution correctly. By defining min and max, does it mean that we use this to transform the data into [0, 1]? 
For example min = 2, max=7, then we transform the data to (data - 2)/5 and drop any values that not fall in [0,1]? Thank you!

**Comment by rezayas** [comment]
You are correct except that we don't need to drop any values. Imagine the user provide `data`. 
- If  `min` and `max` is also provided then set `l = min` and `u = max`, otherwise,
- Set `l = min(data)` and `u = max(data)`
- Build a new variable `transformedData` using `transformedData[i] = (data[i] - l)/(u-l)`
- Fit a Beta distribution to `transformedData`
- Report the parameters of the fitted Beta as well as `l` and `u`.

**Comment by yanqi8** [comment]
Got it, thank you!
For discrete distributions like BetaBinomial and NegativeBinomial, according to wiki, the MLE estimators seem can only be found numerically, and there is no build-in function in Python. So do you want me to write function (or probably using JAGS) to find the Maximum Likelihood Estimators or consider method of moments estimates?

**Comment by rezayas** [comment]
It would be great to have the MLE estimators for these distributions as well. So if it's not too much work, I would give it a try.

Also, I started a separate .py file for moment matching method:
https://github.com/HPM573/HPM573_SupportLib/blob/master/scr/ProbDistParEst.py

A lot of time we don't have access to the original data but just the mean and st-dev of the distribution. Whenever you get a chance, would you also complete this file? Thanks so much Yan!

**Comment by yanqi8** [comment]
OK I will try to work it out. Thanks!

**Comment by yanqi8** [comment]
I just finished the ProbDistFitting.py using Maximum Likelihood Estimation. You can test it in TestProbDistFitting.py. As I defined some Likelihood functions myself, please let me know if you find anything wrong. Thanks!

**Comment by yanqi8** [comment]
For the moment matching method, do we still use AIC to evaluate the fitting?

**Comment by rezayas** [comment]
I haven't thought about it yet. Let's talk about it when we meet.

**Comment by rezayas** [comment]
No rush but I wonder if you have any questions on using parameters for distributions that are consistent across random-number variates and fitting classes.

**Comment by yanqi8** [comment]
Sorry for the delay! I'm working on them and probably could upload an updated version this weekend. 

Actually for the discrete distributions, as there is no build-in function for fitting, I use numeric method to find the ML estimation. But that would give us float number instead of integers for some parameters, like the n in beta-binomial, as optimum solution. Is that OK?

And for moment matching method, as the formulas don't have the loc and scale parameters, I'm not sure how to evaluate them. Could you please give me some advice about it? I thought about use loc=mean, scale=sd, but that seems not right, especially for discrete variables. Thank you!

**Comment by rezayas** [comment]
No worries at all. Let's go case by case, complete as many distributions as you can and we will think about the rest. 

Generally, if the `loc` parameter control the minimum of a random variable, I would like the user to specify that.

**Comment by yanqi8** [comment]
OK. I just updated a version with new argument:
**fixed_location**: specify location, False by default

for continuous distributions, estimate location if fixed_location = False, can also take fixed_location given by users, for example fixed_location = 1 means floc=1

for discrete distribution,  required specify location by users, only take numeric values

I'll think about BetaBinomial, NegativeBinomial and GammaPoisson.

**Comment by rezayas** [comment]
Perfect. 
For Beta, does it make sense to have a `fixed_location` argument? We are already getting  `min` and `max` as optional arguments. Shouldn't the variable `fixed_location` be determined inside the procedure depending on whether `min` is provided?

**Comment by yanqi8** [comment]
For the moment matching methods, I just want to confirm with you that, since we don't have the data, there is no need to **calculate AIC** or **present histograms**. Is that right? Thank you!

**Comment by rezayas** [comment]
That is correct.
