### ISSUE TITLE
Legend in CE Figure

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#20]
For the class `CEA` in [EconEvalClasses.py](https://github.com/HPM573/HPM573_SupportLib/blob/master/scr/EconEvalClasses.py), could you add "Frontier" to the legend of the CE figure when the `show_legend` argument of `show_CE_plane` is `True`?

**Comment by yanqi8** [comment]
Updated.

**Comment by rezayas** [comment]
Great. Something minor. In the legend, could we put "Frontier" at the end of the list?

**Comment by yanqi8** [comment]
OK!

**Comment by rezayas** [comment]
Thank you!
