### ISSUE TITLE
Implement graph_deltaNMB_lines

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#24]

**Comment by yanqi8** [comment]
Could you tell me where is this function? I just couldn't find it 😂 Thank you!

**Comment by rezayas** [comment]
graph_deltaNMB_lines is here (line 611): https://github.com/HPM573/HPM573_SupportLib/blob/master/scr/EconEvalClasses.py

**Comment by yanqi8** [comment]
I just committed a first version of the graph and the test code is in **Test_NMBGraph.py**

**Comment by rezayas** [comment]
Let's use a little bit more realistic test so that we can see how it behaves. 
- use only 3 strategies (s0, s1, and s2)
- change the sampling so that the average cost of these strategies are around $10,000, $20,000 and $50,000
- change the sampling so that the average effect of these strategies are around 0.2, 0.3 and 0.35.
- now the WTP range should be [0, 50,000].

Let's see what we get. Thank you Yan!

**Comment by yanqi8** [comment]
No problem! I updated the test cases. It seems the change of standard deviation of effect has main influence on the shape of the figure.

**Comment by rezayas** [comment]
looks much better. now is it possible to show confidence/prediction region instead of bars? 
something line this but without the dots:

**Comment by rezayas** [comment]
![image](https://user-images.githubusercontent.com/25065190/38426463-b88e5458-3984-11e8-9f61-3aa76928ac4d.png)

**Comment by yanqi8** [comment]
![image](https://user-images.githubusercontent.com/34167870/38428641-460ffeee-398a-11e8-9c86-f822b16f7875.png)
