### ISSUE TITLE
fit_beta_binomial

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#25]
Could you add comments to explain in more details how the maximum likelihood estimates for beta binomial are obtained? Function `fit_beta_binomial` in FittingProbDist_ML.py.

And estimate n from data.

**Comment by yanqi8** [comment]
I changed the function s.t. we can estimate n in ML method. 
For MM method, while we have 3 parameters in total: a, b, n, we won't be able to estimate them using only mean and st_dev.
