### ISSUE TITLE
AIC

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#33]
This is mainly a question. I thought AIC is always positive (but I am not sure at all). If that's true, then we are getting some negative AICs.

**Comment by yanqi8** [comment]
I think AIC could be negative. 
`AIC = -2Ln(L)+ 2k`
If the likelihood is derived from a probability density it can exceed 1, which means that log-likelihood is positive, hence the deviance and the AIC are negative. We can simply choose the smaller AIC no matter it's positive or negative.

ref: https://stats.stackexchange.com/questions/486/negative-values-for-aicc-corrected-akaike-information-criterion/720

**Comment by rezayas** [comment]
Thank you! that totally makes sense.
