### ISSUE TITLE
show_CE_plane

### ISSUE THREAD

**Issue by rezayas** [HPM573/HPM573_SupportLib#36]
This is hopefully easy. Would it be possible to revise the `show_CE_plane` method in EconEvalClasses.py file so that when the range of x or y-axis is less than 10, we let python to automatically format the numbers and ticks (so that the decimal points show up as needed)? 

I had a student whose cost and effect estimates were less than 1, and when she used the `show_CE_plane` method, all tick labels were 0. 

Thanks so much.

**Comment by yanqi8** [comment]
Done! I tried it by setting `x_range=[-1, 1]`, it should work now.

**Comment by rezayas** [comment]
Thank you.. looks great.
